swagger: '2.0'
info:
  title: 华中大相册微信小程序
  version: 1.0.14
  contact:
    name: Mondo
    email: mondogao@gmail.com
host: '127.0.0.0:8080'
basePath: /api/
schemes:
  - http
paths:
  /albums:
    get:
      description: 获取相册列表
      tags:
        - albums
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Album'
  '/albums/{id}':
    get:
      description: 获取相册的信息
      tags:
        - albums
      parameters:
        - $ref: '#/parameters/idPathParam'
      responses:
        '200':
          description: OK
          schema:
            type: object
            allOf:
              - $ref: '#/definitions/Album'
              - type: object
                properties:
                  pictures:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: '#/definitions/Id'
                        src:
                          type: string
  '/albums/{id}/pictures':
    get:
      description: 获取相册下的所有照片信息
      tags:
        - albums
        - pictures
      parameters:
        - $ref: '#/parameters/idPathParam'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Picture'
  '/pictures/{id}/comments':
    post:
      description: 添加评论
      tags:
        - pictures
      parameters:
        - $ref: '#/parameters/sessionParam'
        - $ref: '#/parameters/idPathParam'
        - name: data
          in: body
          schema:
            type: object
            properties:
              content:
                type: string
          required: true
      responses:
        '201':
          description: OK
          schema:
            $ref: '#/definitions/Comment'
  '/pictures/{id}/likes':
    post:
      description: 点赞
      tags:
        - pictures
        - likes
      parameters:
        - $ref: '#/parameters/sessionParam'
        - $ref: '#/parameters/idPathParam'
      responses:
        '201':
          description: OK
  /users:
    put:
      description: 回传小程序发送的用户信息
      tags:
        - users
      parameters:
        - $ref: '#/parameters/sessionParam'
        - name: data
          description: 解密用数据
          in: body
          schema:
            type: object
            properties:
              vi:
                type: string
              signature:
                type: string
              encryptedData:
                type: string
      responses:
        '200':
          description: OK
    post:
      description: 获取 3rd_session
      tags:
        - users
      parameters:
        - name: data
          in: body
          schema:
            type: object
            properties:
              code:
                type: string
      responses:
        '200':
          description: 登陆成功，不会再回传数据
          schema:
            type: object
            properties:
              session:
                $ref: '#/definitions/Session'
        '201':
          description: 注册成功，客户端会再请求加密数据回传
          schema:
            type: object
            properties:
              session:
                $ref: '#/definitions/Session'
definitions:
  Album:
    type: object
    properties:
      id:
        $ref: '#/definitions/Id'
      name:
        type: string
      desc:
        type: string
      coverSrc:
        $ref: '#/definitions/ImageSrc'
      latestUpdateTime:
        type: string
        format: date
      picNum:
        type: integer
  Picture:
    type: object
    properties:
      id:
        $ref: '#/definitions/Id'
      src:
        type: string
      previewSrc:
        $ref: '#/definitions/ImageSrc'
      desc:
        type: string
      uploadDate:
        type: string
        example: '2014-05-30'
      isLiked:
        type: boolean
        description: 根据当前用户返回照片是否被点过赞
      likeTimes:
        type: integer
      author:
        $ref: '#/definitions/User'
      comments:
        type: array
        items:
          $ref: '#/definitions/Comment'
  User:
    type: object
    properties:
      id:
        $ref: '#/definitions/Id'
      username:
        type: string
  Comment:
    type: object
    properties:
      id:
        $ref: '#/definitions/Id'
      commenter:
        $ref: '#/definitions/User'
      content:
        type: string
      date:
        type: string
        example: '2014-05-30'
  Id:
    type: string
  Session:
    type: string
  ImageSrc:
    type: string
    example: /statics/images/9j20-kdj9.png
parameters:
  idPathParam:
    name: id
    in: path
    description: id
    type: string
    required: true
  sessionParam:
    name: 3rd-session
    description: session
    in: header
    type: string
    required: true
